export const REPORT_METADATA_TYPES = [
  "WORKSPACE_REPORT_SAVED",
  "WORKSPACE_REPORT_FILE_CREATED",
  "AGENT_WORKLOAD_REPORT_SAVED",
  "AGENT_QUEUE_STATUS_SAVED",
  "TEMPLATES_CATALOG_SAVED",
  "TEMPLATE_STARTER_PACKS_SAVED",
  "FILES_INVENTORY_REPORT_SAVED",
  "FILE_LINKED_TASKS_REPORT_CREATED",
  "TEAMS_OVERVIEW_REPORT_SAVED",
  "TEAM_STARTER_PACK_HISTORY_SAVED",
  "TEAM_STARTER_ROLLOUT_SUMMARY_SAVED",
  "TEAM_WORKSPACE_REPORT_SAVED",
  "PROJECT_STARTER_PACK_HISTORY_SAVED",
  "PROJECT_STARTER_ROLLOUT_SUMMARY_SAVED",
  "PROJECTS_PORTFOLIO_REPORT_SAVED",
  "PROJECT_BULK_STARTER_PACK_REPORT_SAVED",
  "PROJECT_BULK_SCHEDULER_REPORT_SAVED",
  "OPERATIONS_STATUS_REPORT_SAVED",
  "TASKS_REPORT_SAVED",
  "PROJECT_BOTTLENECKS_REPORT_FILE_CREATED",
  "REPORTS_HISTORY_SAVED"
] as const

const REPORT_METADATA_TYPE_SET = new Set<string>(REPORT_METADATA_TYPES)

export function isReportMetadataType(value: string): value is (typeof REPORT_METADATA_TYPES)[number] {
  return REPORT_METADATA_TYPE_SET.has(value)
}

export const REPORT_METADATA_TYPE_LABELS: Record<(typeof REPORT_METADATA_TYPES)[number], string> = {
  WORKSPACE_REPORT_SAVED: "Workspace Report",
  WORKSPACE_REPORT_FILE_CREATED: "Project Workspace Report",
  AGENT_WORKLOAD_REPORT_SAVED: "Agent Workload Report",
  AGENT_QUEUE_STATUS_SAVED: "Agent Queue Status Report",
  TEMPLATES_CATALOG_SAVED: "Templates Catalog Report",
  TEMPLATE_STARTER_PACKS_SAVED: "Template Starter Packs Catalog",
  FILES_INVENTORY_REPORT_SAVED: "Files Inventory Report",
  FILE_LINKED_TASKS_REPORT_CREATED: "File Linked Tasks Report",
  TEAMS_OVERVIEW_REPORT_SAVED: "Teams Overview Report",
  TEAM_STARTER_PACK_HISTORY_SAVED: "Team Starter Rollout History",
  TEAM_STARTER_ROLLOUT_SUMMARY_SAVED: "Team Starter Rollout Summary",
  TEAM_WORKSPACE_REPORT_SAVED: "Team Workspace Report",
  PROJECT_STARTER_PACK_HISTORY_SAVED: "Project Starter Rollout History",
  PROJECT_STARTER_ROLLOUT_SUMMARY_SAVED: "Project Starter Rollout Summary",
  PROJECTS_PORTFOLIO_REPORT_SAVED: "Projects Portfolio Report",
  PROJECT_BULK_STARTER_PACK_REPORT_SAVED: "Bulk Starter Pack Runner Report",
  PROJECT_BULK_SCHEDULER_REPORT_SAVED: "Bulk Scheduler Runner Report",
  OPERATIONS_STATUS_REPORT_SAVED: "Operations Status Report",
  TASKS_REPORT_SAVED: "Tasks Report",
  PROJECT_BOTTLENECKS_REPORT_FILE_CREATED: "Project Bottlenecks Report",
  REPORTS_HISTORY_SAVED: "Reports History Snapshot"
}

export function reportMetadataTypeLabel(type: string): string {
  if (!isReportMetadataType(type)) return type
  return REPORT_METADATA_TYPE_LABELS[type]
}
